# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-05-09 13:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rectangle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('personID', models.IntegerField()),
                ('frameNum', models.IntegerField()),
                ('top', models.FloatField()),
                ('left', models.FloatField()),
                ('height', models.FloatField()),
                ('width', models.FloatField()),
            ],
        ),
    ]
