# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-05-28 08:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reID', '0002_rectangle_video'),
    ]

    operations = [
        migrations.CreateModel(
            name='TreeEdge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('st', models.IntegerField()),
                ('ed', models.IntegerField()),
                ('val', models.IntegerField()),
            ],
        ),
    ]
